import inspect
import json
import os
import tempfile
import unittest

import project as project_module
from project import ProjectManager


EXPECTED_PROJECT_MANAGER_METHODS = {
    "__init__",
    "_load_chunk_runtime_settings",
    "_copy_chunks_snapshot",
    "_set_chunks_snapshot",
    "_copy_chunk_runtime",
    "_runtime_chunk_fields",
    "_merge_runtime_chunk",
    "set_chunk_runtime",
    "clear_chunk_runtime",
    "mark_chunks_dirty",
    "_chunks_flush_loop",
    "load_paragraphs",
    "save_paragraphs",
    "_load_voice_config",
    "_save_voice_config",
    "_load_app_config",
    "_load_transcription_cache_locked",
    "_save_transcription_cache_locked",
    "_transcription_cache_key",
    "_lookup_cached_transcription",
    "_store_cached_transcription",
    "_copy_cached_transcription_key",
    "_current_script_title",
    "_load_state",
    "_save_state",
    "_prune_legacy_voice_state_fields",
    "load_voice_state_snapshot",
    "replace_voice_state_snapshot",
    "log_voice_audit_event",
    "_normalize_scope_mode",
    "_new_chunk_uid",
    "_ensure_chunk_uids",
    "resolve_chunk_index",
    "is_render_prep_complete",
    "set_render_prep_complete",
    "_init_script_store",
    "shutdown_script_store",
    "reload_script_store",
    "_escape_concat_path",
    "_write_concat_line",
    "_resolve_trim_config",
    "_trim_cache_dir",
    "_build_trim_cache_key",
    "_trim_audio_segment_boundaries",
    "_resolve_export_audio_path",
    "_collect_merge_timeline",
    "_group_timeline_by_chapter",
    "_emit_merge_progress",
    "_create_silence_assets",
    "_pick_silence",
    "_run_ffmpeg_concat",
    "_parse_concat_entries",
    "_ffprobe_audio_summary",
    "_log_concat_failure_diagnostics",
    "_export_concat_mp3",
    "_optimized_export_part_basename",
    "_is_normalization_enabled",
    "_extract_json_object",
    "_detect_channel_count",
    "_loudnorm_codec_args_for_path",
    "_run_ffmpeg_with_progress",
    "_resolve_export_normalization_config",
    "_normalize_audio_file",
    "_call_normalize_audio_file",
    "_load_generation_settings",
    "load_source_document",
    "_split_text_sentences",
    "_count_words",
    "_split_long_chunk_text",
    "_speakers_match",
    "_chunk_in_scope",
    "_chapter_key",
    "_chunks_share_chapter",
    "_join_chunk_text",
    "_merge_adjacent_chunks",
    "_paragraph_mentions_speaker",
    "_chunk_voice_line_counts",
    "_script_voice_line_counts",
    "suggest_design_sample_text",
    "collect_voice_suggestion_context",
    "build_voice_suggestion_prompt",
    "_upsert_clone_manifest_entry",
    "materialize_design_voice",
    "prepare_runtime_voice_config",
    "_normalize_speaker_name",
    "has_voice_config",
    "sync_missing_voice_profiles_from_chunks",
    "reset_voice_state",
    "export_voice_config_compat",
    "export_voice_state_compat",
    "import_voice_compat",
    "get_narrator_threshold",
    "set_narrator_threshold",
    "get_narrator_overrides",
    "_count_name_mentions_in_text",
    "rank_chapter_narration_candidates",
    "get_auto_narrator_aliases",
    "_apply_narrator_override",
    "set_narrator_override",
    "disable_narrator_narration_and_reassign_chapters",
    "get_chapter_narrator_voice_repair",
    "ensure_chapter_narrator_voice_can_narrate",
    "compute_auto_narrator_aliases",
    "refresh_auto_narrator_aliases",
    "_count_speaker_lines",
    "_resolve_narrator_name",
    "resolve_voice_speaker",
    "_voice_entry_from_config",
    "_voice_ref_audio_from_config",
    "_voice_generation_issue_from_config",
    "validate_generation_voice_targets",
    "preview_voice_config_invalidation",
    "invalidate_chunk_audio_indices",
    "save_voice_config_with_invalidation",
    "get_engine",
    "unload_tts_engine",
    "_load_asr_settings",
    "get_asr_engine",
    "_clear_proofread_state",
    "_allowed_proofread_speaker_slugs",
    "_expand_common_abbreviation_words",
    "_score_proofread_normalized_texts",
    "_proofread_similarity_metrics",
    "_build_chunk_proofread_result",
    "_commit_proofread_result_locked",
    "_commit_proofread_results_batch_locked",
    "_discarded_proofread_state",
    "_cached_chunk_transcript_text",
    "_cached_chunk_audio_validation",
    "_manually_mark_proofread_clip",
    "manually_validate_proofread_clip",
    "manually_reject_proofread_clip",
    "compare_proofread_clip",
    "discard_proofread_selection",
    "_reset_stale_proofread_scope_locked",
    "_normalize_asr_text",
    "_normalize_asr_words",
    "_proofread_duration_outlier_seconds_for_text",
    "_proofread_should_force_asr_for_short_audio",
    "_asr_similarity_score",
    "transcribe_audio_path",
    "transcribe_audio_paths_bulk",
    "_load_chunks_from_disk_locked",
    "load_chunks_raw",
    "load_chunks_view",
    "load_chunks",
    "get_chunk_raw",
    "get_chunks_by_uids",
    "get_chapter_chunks",
    "get_chapter_list",
    "resolve_generation_targets",
    "_resolve_chunk_audio_full_path",
    "get_chunk_audio_ref",
    "_publish_chunk_upsert",
    "_publish_chunk_delete",
    "_publish_chapter_deleted",
    "_publish_chapter_list_changed",
    "get_chunk_view",
    "get_chunk_view_by_index",
    "_chunk_has_generated_work",
    "_script_sync_match_key",
    "_preserve_chunk_state_for_script_sync",
    "sync_chunks_from_script_if_stale",
    "reconcile_chunk_audio_states",
    "_validate_chunk_audio",
    "_validate_audio_path_for_chunk",
    "get_chunk_chapter_summary",
    "get_audio_coverage_summary",
    "has_generated_chunk_audio",
    "export_chunks_to_path",
    "has_substantive_chunks",
    "_parse_chunk_audio_candidate_name",
    "_discarded_voicelines_dir",
    "_collect_repair_candidates_from_dir_locked",
    "_move_candidate_to_discarded_locked",
    "_build_lost_audio_repair_text_index",
    "_build_repair_match_cache",
    "_build_speaker_word_frequency_cache",
    "_drop_low_frequency_transcript_words",
    "_remove_selected_words",
    "_candidate_indices_for_discarded_match",
    "_best_discarded_repair_match",
    "_candidate_nearby_chunk_indices",
    "_candidate_anchor_chapter",
    "_candidate_same_chapter_indices",
    "_find_asr_repair_match",
    "repair_lost_audio_links",
    "proofread_chunks",
    "clear_proofread_failures",
    "recover_interrupted_generating_chunks",
    "load_script_document",
    "load_dictionary_entries",
    "_count_audio_linked_chunks",
    "_load_chunk_backup_document",
    "_load_chunk_backup_audio_count",
    "_update_chunks_backups",
    "_atomic_json_write_raw",
    "_atomic_json_write",
    "save_chunks",
    "_commit_chunk_updates",
    "patch_chunk_if",
    "patch_chunks_if",
    "claim_generation",
    "claim_generation_many",
    "reset_generation_rows",
    "prepare_chunk_for_regeneration_by_uid",
    "delete_chunk_by_uid",
    "delete_chapter_by_name",
    "_update_chunk_fields",
    "_claim_chunk_generation",
    "_claim_chunks_generation",
    "_chunk_token_matches",
    "chunk_has_generation_token",
    "_update_chunk_fields_if_token",
    "force_reset_chunks_to_pending",
    "reset_generating_chunks",
    "insert_chunk",
    "insert_silence_chunk",
    "delete_chunk",
    "delete_chapter",
    "restore_chunk",
    "repair_legacy_chunk_order",
    "_legacy_audio_index_from_path",
    "_stable_audio_uid_from_path",
    "invalidate_stale_audio_references",
    "decompose_long_segments",
    "merge_orphan_segments",
    "update_chunk",
    "prepare_chunk_for_regeneration",
    "_load_tts_settings",
    "_get_auto_regen_retry_attempts",
    "_load_generation_chunks",
    "_speaker_line_counts_for_chunks",
    "_resolve_generation_speaker",
    "_cleanup_temp_file",
    "_store_generated_audio",
    "_chunk_audio_filename_base",
    "_repair_target_audio_path_locked",
    "_commit_repaired_chunk_locked",
    "_runtime_chunk_state",
    "_chunk_token_matches_live",
    "register_audio_finalization_listener",
    "unregister_audio_finalization_listener",
    "_notify_audio_finalize_listener",
    "_audio_finalize_worker_loop",
    "_finalize_retry_requested",
    "_spool_audio_relative_path",
    "_spool_audio_full_path",
    "_apply_runtime_patch_to_chunk",
    "flush_dirty_chunks",
    "_enqueue_audio_finalize_task",
    "list_audio_finalize_tasks",
    "has_pending_audio_finalize_tasks",
    "clear_audio_finalize_tasks",
    "_process_audio_finalize_task",
    "_finalize_generated_audio",
    "_generate_chunk_audio_internal",
    "generate_chunk_audio",
    "merge_audio",
    "export_optimized_mp3_zip",
    "export_audacity",
    "merge_m4b",
    "_escape_ffmeta",
    "_build_m4b_chapters",
    "generate_chunks_parallel",
    "_group_indices_by_voice_type",
    "group_indices_by_resolved_speaker",
    "generate_chunks_batch",
}

EXPECTED_PROJECT_EXPORTS = {
    "ProjectManager",
    "_coerce_bool",
    "get_speaker",
    "_is_structural_text",
    "_extract_chapter_name",
    "_build_chunk",
    "group_into_chunks",
    "script_entries_to_chunks",
    "MAX_CHUNK_CHARS",
    "PROOFREAD_DURATION_OUTLIER_SECONDS",
    "PROOFREAD_LONG_CHUNK_WORD_THRESHOLD",
    "PROOFREAD_LONG_CHUNK_DURATION_OUTLIER_SECONDS",
    "PROOFREAD_SHORT_AUDIO_FORCE_ASR_SECONDS",
    "PROOFREAD_BATCH_COMMIT_SIZE",
    "REPAIR_BATCH_COMMIT_SIZE",
    "CHAPTER_HEADING_RE",
    "COMMON_PROOFREAD_ABBREVIATIONS",
    "TRIM_CACHE_VERSION",
    "TRIM_SILENCE_THRESHOLD_DBFS",
    "TRIM_MIN_SILENCE_LEN_MS",
    "TRIM_KEEP_PADDING_MS",
}

EXPECTED_SIGNATURES = {
    "resolve_chunk_index": "(self, chunk_ref, chunks=None)",
    "load_chunks_view": "(self, chapter=None)",
    "save_chunks": "(self, chunks)",
    "update_chunk": "(self, chunk_ref, data)",
    "prepare_chunk_for_regeneration": "(self, chunk_ref)",
    "generate_chunk_audio": "(self, index, attempt=0, generation_token=None)",
    "generate_chunks_parallel": "(self, indices, max_workers=2, progress_callback=None, cancel_check=None, item_callback=None, generation_token=None, item_started_callback=None)",
    "generate_chunks_batch": "(self, indices, batch_seed=-1, batch_size=4, progress_callback=None, batch_group_by_type=False, cancel_check=None, item_callback=None, generation_token=None, item_started_callback=None)",
    "merge_audio": "(self, progress_callback=None, log_callback=None, export_config=None, chapter=None)",
    "merge_m4b": "(self, per_chunk_chapters=False, metadata=None, export_config=None)",
    "proofread_chunks": "(self, chapter=None, threshold=1.0, progress_callback=None)",
    "repair_lost_audio_links": "(self, use_asr=True, progress_callback=None, rejected_only=False)",
    "set_render_prep_complete": "(self, complete=True)",
    "transcribe_audio_paths_bulk": "(self, relative_audio_paths, progress_callback=None)",
}


class ProjectManagerContractTests(unittest.TestCase):
    def test_project_manager_method_surface(self):
        actual = set()
        for name in dir(ProjectManager):
            if name.startswith("__") and name != "__init__":
                continue
            member = getattr(ProjectManager, name, None)
            if inspect.isroutine(member):
                actual.add(name)
        self.assertEqual(actual, EXPECTED_PROJECT_MANAGER_METHODS)

    def test_project_manager_selected_signatures(self):
        for method_name, signature in EXPECTED_SIGNATURES.items():
            self.assertEqual(str(inspect.signature(getattr(ProjectManager, method_name))), signature)

    def test_project_module_exports_expected_symbols(self):
        module_names = set(dir(project_module))
        self.assertTrue(EXPECTED_PROJECT_EXPORTS.issubset(module_names))

    def test_project_manager_internal_guards(self):
        with tempfile.TemporaryDirectory() as root_dir:
            os.makedirs(os.path.join(root_dir, "app"), exist_ok=True)
            os.makedirs(os.path.join(root_dir, "voicelines"), exist_ok=True)
            with open(os.path.join(root_dir, "annotated_script.json"), "w", encoding="utf-8") as f:
                json.dump({"entries": [], "dictionary": []}, f)
            manager = ProjectManager(root_dir)
            try:
                self.assertTrue(hasattr(manager, "_transcription_cache_lock"))
                self.assertTrue(hasattr(manager, "_transcription_cache"))
                self.assertTrue(callable(getattr(manager, "_load_voice_config")))
                self.assertTrue(callable(getattr(manager, "_resolve_trim_config")))
                self.assertTrue(callable(getattr(manager, "_validate_chunk_audio")))
            finally:
                manager.flush_dirty_chunks(force=True)
                manager.shutdown_script_store(flush=True)

    def test_chunks_json_direct_access_is_limited(self):
        repo_root = os.path.dirname(__file__)
        allowed = {
            os.path.join(repo_root, "script_provider.py"),
            os.path.join(repo_root, "scripts", "create_script.py"),
            os.path.join(repo_root, "scripts", "generate_script.py"),
            os.path.join(repo_root, "test_project_archive.py"),
            os.path.join(repo_root, "test_workflow_entrypoints.py"),
        }
        forbidden_hits = []

        for current_root, _, filenames in os.walk(repo_root):
            for filename in filenames:
                if not filename.endswith(".py"):
                    continue
                path = os.path.join(current_root, filename)
                if path in allowed or path == __file__:
                    continue
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                if "with open(self.chunks_path" in content or "with open(CHUNKS_PATH" in content:
                    forbidden_hits.append(os.path.relpath(path, repo_root))

        self.assertEqual(forbidden_hits, [])
